---
title: "NMDS Plotting: trnL"
author: "Ellen Bledsoe"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r libraries_functions_data, echo = FALSE, include = FALSE}
# maybe move Rmd file to general folder rather than in scripts
# might fix some of the issues we're dealing with here
source('Scripts/NMDS_for_markdown_trnL.R')
# and maybe save results as data so it doesn't have to process every time I want to try to render?
```

## Plot 1
* 2017 data
* binary (presence/absence)
* trnL 
* all potential millet removed

```{r figure1, fig.height = 8.83, fig.width = 9.58, fig.align = "center", include = TRUE}
plot1
```

## Plot 2
* 2016 data
* binary (presence/absence)
* trnL 
* all potential millet removed

```{r figure2, fig.height = 8.83, fig.width = 11, fig.align = "center", include = TRUE}
plot2
```

## Plot 3
* 2017 data
* PP only = proportions
* trnL 
* all potential millet removed

```{r figure3, fig.height = 8.83, fig.width = 10.2, fig.align = "center", include = TRUE}
plot3
```

## Plot 4
* 2016 data
* PP only = proportions
* trnL 
* all potential millet removed
```{r figure4, fig.height = 8.83, fig.width = 11, fig.align = "center", include = TRUE}
plot4
```